// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSaaOKdgL5KoTPCynk1WKVFR_f7JimikQ',
    appId: '1:622783495290:web:032312d91cd6eb26fc8fc3',
    messagingSenderId: '622783495290',
    projectId: 'timeexplorer-fyp',
    authDomain: 'timeexplorer-fyp.firebaseapp.com',
    storageBucket: 'timeexplorer-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByykdHs69QHyWv7Py5_XNi8OJo-6w9hKg',
    appId: '1:622783495290:android:f57934b4e1af653ffc8fc3',
    messagingSenderId: '622783495290',
    projectId: 'timeexplorer-fyp',
    storageBucket: 'timeexplorer-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXt3D1rYPvbrZCUJ5rdNKdCkygF-bHs3Y',
    appId: '1:622783495290:ios:e2c4f3d7e91916fffc8fc3',
    messagingSenderId: '622783495290',
    projectId: 'timeexplorer-fyp',
    storageBucket: 'timeexplorer-fyp.firebasestorage.app',
    androidClientId: '622783495290-ennq3abqv6qaat9flr3utum1gb29sh05.apps.googleusercontent.com',
    iosClientId: '622783495290-5ltmda1dacn6cecannh459a953vce5nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeexplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXt3D1rYPvbrZCUJ5rdNKdCkygF-bHs3Y',
    appId: '1:622783495290:ios:e2c4f3d7e91916fffc8fc3',
    messagingSenderId: '622783495290',
    projectId: 'timeexplorer-fyp',
    storageBucket: 'timeexplorer-fyp.firebasestorage.app',
    androidClientId: '622783495290-ennq3abqv6qaat9flr3utum1gb29sh05.apps.googleusercontent.com',
    iosClientId: '622783495290-5ltmda1dacn6cecannh459a953vce5nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeexplorer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSaaOKdgL5KoTPCynk1WKVFR_f7JimikQ',
    appId: '1:622783495290:web:96dc26466745d0c0fc8fc3',
    messagingSenderId: '622783495290',
    projectId: 'timeexplorer-fyp',
    authDomain: 'timeexplorer-fyp.firebaseapp.com',
    storageBucket: 'timeexplorer-fyp.firebasestorage.app',
  );

}