analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3472885,"name"\:"First Project","teamId"\:3458653,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3494639,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3458653,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
