import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:timeexplorer/core/theme/app_theme.dart';

class PolicyPage extends StatelessWidget {
  final String title;
  const PolicyPage({super.key, required this.title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text(
          title,
          style: GoogleFonts.plusJakartaSans(
            fontWeight: FontWeight.w800,
            color: AppTheme.onSurface,
          ),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, color: AppTheme.onSurface),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(24, 8, 24, 40),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Last Updated: May 2025',
              style: GoogleFonts.beVietnamPro(
                color: AppTheme.onSurfaceVariant,
                fontStyle: FontStyle.italic,
                fontSize: 13,
              ),
            ),
            const SizedBox(height: 24),
            _buildSection(
              'Welcome to Time Explorer',
              'Time Explorer ("we", "our", "the app") is an educational mobile application that lets you explore history through AI-powered conversations, quizzes, places, and gamified learning. This Privacy Policy explains how we collect, use, and protect your data.',
            ),
            _buildSection(
              '1. Data We Collect',
              '• Account information: email address, display name, and date of birth provided during registration.\n'
              '• Profile data: profile photo uploaded to Firebase Storage.\n'
              '• Usage data: places explored, quiz scores, XP, streak count, badges, and learning progress — stored in Firestore.\n'
              '• Notifications: device token stored to send local push notifications about your learning streak.',
            ),
            _buildSection(
              '2. Firebase & Google Services',
              'Time Explorer uses Firebase (by Google) for authentication, cloud database (Firestore), and file storage. Firebase may collect analytics data as described in the Firebase Privacy Policy. We do not sell your data to third parties.',
            ),
            _buildSection(
              '3. AI-Generated Content (Gemini)',
              'Time Explorer uses Google Gemini AI to generate historical character responses, place insights, and quiz content. Content generated by AI may not be fully accurate. All AI responses are for educational purposes only and should not be treated as authoritative historical fact.\n\nYour chat messages with historical figures are processed by the Gemini API. We do not store the full contents of AI conversations beyond your active session.',
            ),
            _buildSection(
              '4. Camera & Media Access',
              'We request access to your camera and photo gallery solely to allow you to update your profile photo. Images are uploaded to Firebase Storage and are associated only with your account. We do not access your camera or gallery for any other purpose.',
            ),
            _buildSection(
              '5. Notifications',
              'We send local push notifications to remind you of daily learning streaks and new content. You can disable notifications at any time in your device settings or in the app Settings → Notifications.',
            ),
            _buildSection(
              '6. Data Retention',
              'Your data is retained as long as your account is active. You may delete your account at any time from Settings → Delete Account. This permanently removes your Firebase Auth account and all associated Firestore data.',
            ),
            _buildSection(
              '7. Children\'s Privacy',
              'Time Explorer is designed for users aged 13 and above. We do not knowingly collect personal data from children under 13. If you believe a child under 13 has provided us personal data, please contact us so we can delete it.',
            ),
            _buildSection(
              '8. Your Rights',
              '• Access: You can view your personal info in the Profile section.\n'
              '• Correction: You can update your display name and photo in Edit Profile.\n'
              '• Deletion: You can delete your account and all data from Settings.\n'
              '• Contact: For any privacy concerns, contact us at usmansardar037@gmail.com.',
            ),
            _buildSection(
              '9. Changes to this Policy',
              'We may update this policy from time to time. The "Last Updated" date at the top of this page reflects the most recent revision. Continued use of the app after changes constitutes acceptance of the updated policy.',
            ),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppTheme.primaryContainer.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(
                  color: AppTheme.primaryContainer.withValues(alpha: 0.2),
                ),
              ),
              child: Row(
                children: [
                  const Icon(Icons.mail_outline_rounded, color: AppTheme.primaryContainer, size: 20),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'Questions? Contact us at usmansardar037@gmail.com',
                      style: GoogleFonts.beVietnamPro(
                        fontSize: 13,
                        color: AppTheme.onSurface,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(String heading, String body) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            heading,
            style: GoogleFonts.plusJakartaSans(
              fontSize: 16,
              fontWeight: FontWeight.w800,
              color: AppTheme.onSurface,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            body,
            style: GoogleFonts.beVietnamPro(
              fontSize: 14,
              height: 1.6,
              color: AppTheme.onSurfaceVariant,
            ),
          ),
        ],
      ),
    );
  }
}
